# Generated by Django 4.1.3 on 2022-11-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_pk",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nickname", models.CharField(max_length=10, null=True)),
                ("school_name", models.CharField(max_length=100)),
                ("id", models.CharField(max_length=16)),
                ("pw", models.CharField(max_length=16)),
            ],
            options={"db_table": "User",},
        ),
        migrations.CreateModel(
            name="User_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information_pk", models.CharField(max_length=100)),
                ("p_number", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                (
                    "user_pk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kimlee1031.user",
                    ),
                ),
            ],
            options={"db_table": "User_information",},
        ),
        migrations.CreateModel(
            name="Taxi_posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_posts", models.CharField(max_length=50)),
                ("post_name", models.CharField(max_length=100)),
                ("post_content", models.DateTimeField()),
                (
                    "user_pk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kimlee1031.user",
                    ),
                ),
            ],
            options={"db_table": "Taxi_posts",},
        ),
    ]
