# Generated by Django 4.1.3 on 2022-11-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kimlee1031", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="Userkimsang",),
    ]
