# Generated by Django 4.1.3 on 2022-11-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kimlee1031", "0003_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="Userkimsang",),
    ]
